version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default
  db:
    image: postgres
    environment:
      POSTGRES_DB: tokenist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Daniyal10!
    ports:
      - "5432:5432"
    networks:
      - default
networks:
  default:
      name: app
      external: false
      driver: bridge

