version: '3'

services:
  web:
    image: my-django-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_DB: tokenist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Daniyal10!
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
